feature: providing a minimal launcher written in flutter for ubuntu frame
canonical/ubuntu-frame pull request #191
Opened 2024-06-24 12:47 UTC by mattkae

## What's new?
- Frame can now optionally support the `launcher`, which is a minimal dock allowing the user to switch between fullscreen application

2024-06-24 12:49 UTC, Saviq commented
@mattkae can you please draft a documentation page for this? Particularly on what are the requirements for an icon to show up.

Just pop it in here and we'll copy to Discourse Docs when ready (or just publish on DD already with a "Work in progress" note).

2024-06-24 12:50 UTC, Saviq commented on README.md
> +snap connect ubuntu-frame:desktop-launch
We [should ask](https://forum.snapcraft.io/c/store-requests/19) for it to be autoconnected instead.

2024-06-24 12:58 UTC, Saviq reviewed
Oh and you'll need this to please the review tools:

```diff
diff --git a/snap/local/plugs.json b/snap/local/plugs.json
new file mode 100644
index 0000000..426efa7
--- /dev/null
+++ b/snap/local/plugs.json
@@ -0,0 +1,5 @@
+{
+  "desktop-launch":{
+    "allow-installation": "true"
+  }
+}
```

2024-06-24 14:14 UTC, mattkae commented
> Oh and you'll need this to please the review tools:
> 
> ```diff
> diff --git a/snap/local/plugs.json b/snap/local/plugs.json
> new file mode 100644
> index 0000000..426efa7
> --- /dev/null
> +++ b/snap/local/plugs.json
> @@ -0,0 +1,5 @@
> +{
> +  "desktop-launch":{
> +    "allow-installation": "true"
> +  }
> +}
> ```



> Oh and you'll need this to please the review tools:
> 
> ```diff
> diff --git a/snap/local/plugs.json b/snap/local/plugs.json
> new file mode 100644
> index 0000000..426efa7
> --- /dev/null
> +++ b/snap/local/plugs.json
> @@ -0,0 +1,5 @@
> +{
> +  "desktop-launch":{
> +    "allow-installation": "true"
> +  }
> +}
> ```

https://github.com/canonical/ubuntu-frame/actions/runs/9646782833/job/26604055393?pr=191 I am still seeing an error. Did I do it right? Just populated `snap/local/plugs.json` with:

```json
{
  "desktop-launch": {
    "allow-installation": "true"
  }
}
```

2024-06-24 14:31 UTC, mattkae commented on README.md
> +snap connect ubuntu-frame:desktop-launch
https://forum.snapcraft.io/t/request-for-interface-auto-connection-for-the-desktop-launch-interface/40734

2024-06-24 16:08 UTC, Saviq commented on scripts/bin/run-client-wait
> +#!/bin/sh
Just call it `wayland-launch` so we know where it's coming from?

2024-06-24 17:09 UTC, Saviq commented
Please add copyright headers to the new files, too

2024-06-24 17:34 UTC, mattkae commented
@Saviq: I just have the remaining question here about CI being broken. Documentation is in the description.

2024-06-24 17:38 UTC, Saviq commented
Hmm Send button failed. We need the store ACK for this to pass now.

2024-06-25 09:52 UTC, Saviq approved these changes
Tiny tweaks, otherwise good!

(but we need to wait for the store ACK before landing)

2024-06-25 09:52 UTC, Saviq commented on snap/hooks/configure
> +# (Re)start the launcher
```suggestion
# Start or stop the launcher
```

2024-06-25 09:52 UTC, Saviq commented on scripts/bin/wayland-launch
> +
We should have the `snapctl is-connected` check here for `desktop-launch opengl wayland`. Maybe not the `setup.sh` script, but at least the warning.

2024-06-25 12:38 UTC, Saviq commented on scripts/bin/wayland-launch
> +fi
```suggestion
for PLUG in desktop-launch opengl wayland; do
  if ! snapctl is-connected ${PLUG}
  then
    echo "WARNING: ${PLUG} interface not connected"
  fi
done
```

2024-07-16 11:50 UTC, Saviq commented
@mattkae we'll need to disable this for `armhf`, since Flutter doesn't support it.

See https://github.com/canonical/mir-test-tools/blob/7e593d47308ed20608d634b8b2525bb1df12bc2a/snap/snapcraft.yaml#L211-L229 for reference

2024-07-16 12:21 UTC, Saviq commented on snap/hooks/configure
> +if [ "$(snapctl get launcher)" = "true" ]; then
We should fail here if on `armhf`

2024-07-16 12:37 UTC, Saviq commented on snap/hooks/configure
> +    echo "Cannot enable the launcher on an armhf system"
We also build for risc, so best reverse that. Maybe there's something in the environment we can use?

2024-07-16 12:45 UTC, Saviq commented on snap/hooks/configure
> +    echo "Cannot enable the launcher on an armhf system"
Reverse as in have an allow-list, not a deny-list

2024-07-16 13:51 UTC, Saviq commented on snap/hooks/configure
> +  if [[ "$ARCH" != x86_64* ]] && [[ "$ARCH" != i*86 ]] && [[ "$ARCH" != arm64 ]]; then
```suggestion
  if [[ "$ARCH" != @(x86_64*|i*86|arm64) ]]; then
```

I only learned this recently, too ;)

2024-07-16 15:59 UTC, mattkae commented
@Saviq Do you know what CI is angry about?

```
remote: Create a merge proposal for 'main' on Launchpad by visiting:
remote:       https://code.launchpad.net/~mir-ci-bot/mir-ci-bot-craft-remote-build/+git/snapcraft-ubuntu-frame-92e4eac9d32b978bbdb01c7959f0fcb9/+ref/main/+register-merge

```

2024-07-16 16:01 UTC, Saviq commented
> @Saviq Do you know what CI is angry about?

It just timed out, looks like LP went on hiatus.

The "merge proposal" message is always there, just INFO when pushing to Launchpad git.

2024-07-17 12:06 UTC, Saviq commented on snap/snapcraft.yaml
>        - wayland
Sorry, we should actually reverse this and have a `wayplug` instead. Some of our scripting relies on the `:wayland` slot being there - and it's the more important side anyway.

2024-07-18 05:23 UTC, Saviq commented on snap/snapcraft.yaml
>        - wayland
@mattkae so this is the last bit here, I believe.

2024-07-18 05:24 UTC, Saviq commented on scripts/bin/wayland-launch
> +for PLUG in desktop-launch opengl wayland; do
```suggestion
for PLUG in desktop-launch opengl wayplug; do
```

2024-07-18 13:59 UTC, mattkae commented on snap/snapcraft.yaml
>        - wayland
Done!

2024-07-25 16:33 UTC, Saviq commented
@AlanGriffiths since I was all over this, would you please have a look here, disregarding the `launcher/` folder - just the snap stuff?

2024-07-25 16:33 UTC, Saviq approved these changes
This all looks good to me, just tweaked some of the snap details.

2024-07-25 16:50 UTC, AlanGriffiths requested changes
Looks sensible. Just one nit about disconnecting `desktop-launch` without disabling the "launcher"

2024-07-25 16:50 UTC, AlanGriffiths commented on snap/hooks/configure
> +  fi
Probably want to either:

1. mention changing the `launcher` config option too.
2. reset the `launcher` config option if/when the `desktop-launch` interface is disconnected

2024-07-26 08:07 UTC, Saviq commented on snap/hooks/configure
> +  fi
I'm of two minds... with this we're guiding users how to make things fully work, not sure we need the reverse. We do warn that `desktop-launch` is disconnected, in `wayland-launch`. And the launcher will still work, just not show the icons...

2024-07-26 08:54 UTC, Saviq commented on snap/hooks/configure
> +  fi
OK I'm convinced. Added a disconnect hook as leaving the launcher on would cause subsequent `configure` script failures e.g. on refresh otherwise.

2024-07-26 10:19 UTC, merged